# Deploy app code outside `public_html`, and copy the contents of `public/`
# into the subdirectory document root.
deployment:
  tasks:
    - export APPPATH=/home/ixbwdbzy/bsas
    - export PUBLICPATH=/home/ixbwdbzy/public_html/bsas
    - export WRITEPATH=/home/ixbwdbzy/bsas/writable
    - /bin/mkdir -p $APPPATH
    - /bin/mkdir -p $PUBLICPATH
    - /bin/mkdir -p $WRITEPATH/cache
    - /bin/mkdir -p $WRITEPATH/debugbar
    - /bin/mkdir -p $WRITEPATH/logs
    - /bin/mkdir -p $WRITEPATH/session
    - /bin/mkdir -p $WRITEPATH/uploads
    - /bin/find $APPPATH -mindepth 1 -maxdepth 1 ! -name writable -exec rm -rf {} \;
    - /bin/find $PUBLICPATH -mindepth 1 -maxdepth 1 -exec rm -rf {} \;
    - /bin/cp -R app $APPPATH
    - /bin/cp composer.json $APPPATH
    - /bin/cp composer.lock $APPPATH
    - /bin/cp spark $APPPATH
    - /bin/cp env $APPPATH/.env
    - /bin/sh -c 'if [ -x /opt/cpanel/composer/bin/composer ]; then /opt/cpanel/composer/bin/composer install --no-dev --working-dir="$APPPATH"; else composer install --no-dev --working-dir="$APPPATH"; fi'
    - /bin/cp -R public/. $PUBLICPATH
    - /bin/chmod -R 775 $WRITEPATH
